import { ScreenTutorial } from './types';

const tutorials: ScreenTutorial[] = [
  // ═══════════════════════════════════════════════════════════════
  // DASHBOARD
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-dashboard',
    screenPath: '/',
    screenName: 'Dashboard',
    title: 'Dashboard Overview',
    description: 'Learn how to monitor your business health, track key metrics, and access quick actions from the Dashboard.',
    estimatedDuration: 5,
    steps: [
      {
        id: 'dashboard-welcome',
        title: 'Welcome to Your Dashboard',
        description: 'The Dashboard is your command center. It gives you a real-time snapshot of your business performance, including revenue, expenses, profit, and key alerts.',
        instruction: 'Take a moment to scan the summary cards at the top. These show your total revenue, expenses, profit, and outstanding debts for the current period.',
        tooltipPosition: 'center',
      },
      {
        id: 'dashboard-health-score',
        title: 'Business Health Score',
        description: 'Your Business Health Score summarizes overall performance. A higher score means your business is running efficiently.',
        instruction: 'Look at the health score gauge in Settings. Green means healthy, yellow means caution, and red means action needed. Click the settings icon in the sidebar to view your full health score with detailed breakdown.',
        targetSelector: 'div[data-slot="card"]',
        tooltipPosition: 'bottom',
      },
      {
        id: 'dashboard-alerts',
        title: 'Alerts & Notifications',
        description: 'Stay informed about low stock, unpaid debts, expiring items, and other important events. Alerts appear here so nothing slips through the cracks.',
        instruction: 'Review any active alerts. Each alert shows severity (warning, error, or info) and a brief message about what needs attention.',
        tooltipPosition: 'center',
      },
      {
        id: 'dashboard-charts',
        title: 'Sales & Revenue Charts',
        description: 'Visualize your sales trends over time. These charts help you spot patterns, peak seasons, and areas for improvement.',
        instruction: 'The Revenue Intelligence chart shows your sales over time. Use the period selector (Week/Month/Year) above the chart to switch between views.',
        targetSelector: 'svg.recharts-surface',
        tooltipPosition: 'top',
      },
      {
        id: 'dashboard-quick-actions',
        title: 'Business Assistant',
        description: 'The Business Assistant provides actionable insights and suggestions based on your data, helping you make informed decisions.',
        instruction: 'Read the assistant\'s suggestions below. Each card offers a specific action you can take to improve your business.',
        tooltipPosition: 'center',
      },
      {
        id: 'dashboard-summary',
        title: 'You\'re All Set!',
        description: 'You now understand the Dashboard. Use it daily to monitor performance, catch issues early, and make data-driven decisions.',
        instruction: 'Best Practice: Check your Dashboard at the start of each day. Review alerts first, then scan metrics, and finally check charts for trends.',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // INVENTORY — Add Item form (12+ fields), Purchase Order, Details
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-inventory',
    screenPath: '/inventory',
    screenName: 'Inventory',
    title: 'Inventory Management',
    description: 'Learn how to add, manage, and track inventory items, create purchase orders, and monitor stock levels.',
    estimatedDuration: 12,
    steps: [
      {
        id: 'inv-welcome',
        title: 'Managing Your Inventory',
        description: 'The Inventory screen is where you track all products. You can add new items, update stock, manage suppliers, and create purchase orders.',
        instruction: 'The data table shows all your inventory items. You can search, filter by category or date, and sort any column.',
        targetSelector: 'div.overflow-auto.rounded-xl.border',
        tooltipPosition: 'bottom',
      },
      {
        id: 'inv-search',
        title: 'Search & Filter Inventory',
        description: 'Quickly find items using the search bar or apply filters to narrow down by category, date range, or credit status.',
        instruction: 'Type in the search box to filter items by name. Click the Filter button to explore advanced filtering options by date range, category, or credit status.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'inv-add-open',
        title: 'Opening the Add Item Form',
        description: 'Click "Add Item" to open the registration form. You\'ll enter product details, pricing, units, and supplier information.',
        instruction: 'Click the Add Item button (Plus icon) to open the form. We\'ll walk through every field together.',
        targetSelector: 'button:has(svg.lucide-plus)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'inv-add-name',
        title: 'Item Name (Required)',
        description: 'Enter the product name. This is how the item will appear everywhere — in sales, reports, and search results.',
        instruction: 'Type a descriptive name. Example: "Whole Wheat Flour — 5kg Bag". Be specific so you can find it easily later.',
        targetSelector: 'input[data-slot="input"][placeholder*="product" i]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'inv-add-brand',
        title: 'Brand / Company Name',
        description: 'Enter the manufacturer or brand name. This helps distinguish similar products from different suppliers.',
        instruction: 'Type the brand name, e.g. "Mama Fresh" or leave blank if unbranded. This field is optional.',
        targetSelector: 'input[data-slot="input"][placeholder*="brand" i]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'inv-add-quality',
        title: 'Quality Grade',
        description: 'Assign a quality grade to the item. This helps with inventory valuation and sorting.',
        instruction: 'Enter a grade like "Grade A", "Premium", or "Standard". This is optional but useful for inventory analysis.',
        targetSelector: 'input[data-slot="input"][placeholder*="quality" i]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'inv-add-category',
        title: 'Category Selection',
        description: 'Categories organize your inventory. Choose an existing category or create a new one on the fly.',
        instruction: 'Select a category from the dropdown. If none fits, click the Plus button next to it to create a new category like "Bakery" or "Beverages".',
        targetSelector: 'button[data-slot="select-trigger"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'inv-add-units',
        title: 'Purchase & Base Units',
        description: 'Define how you buy and sell the item. Purchase unit is what you order (e.g. box), base unit is what you sell (e.g. piece).',
        instruction: 'Purchase Unit: "Box" or "Crate". Base Unit: "Piece" or "Kg". Set Units Per Pack (e.g. 20 pieces per box) and Initial Stock in packs.',
        targetSelector: 'input[data-slot="input"][placeholder*="Box" i]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'inv-add-pricing',
        title: 'Pricing Configuration',
        description: 'Enter purchase costs and selling prices for both pack and base units. The system calculates profit margins automatically.',
        instruction: 'Fill in Pack Cost (what you pay per box), Base Cost (per piece), Pack Price (selling price per box), and Base Price (selling price per piece).',
        targetSelector: 'input[data-slot="input"][type="number"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'inv-add-sell-units',
        title: 'Enable Unit Sales',
        description: 'Choose whether customers can buy this item by base unit (piece), pack unit (box), or both.',
        instruction: 'Toggle the switches: enable "Sell by Base Unit" to allow single-piece sales, enable "Sell by Pack Unit" to allow box sales. Most items need both.',
        targetSelector: 'button[data-slot="switch"][role="switch"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'inv-add-supplier',
        title: 'Supplier & Expiry',
        description: 'Link the item to a supplier and set an expiry date if applicable. This is critical for perishable goods.',
        instruction: 'Select a supplier from the dropdown. Set the expiry date if the item is perishable. Enable "Credit Purchase" if buying on credit terms.',
        targetSelector: 'input[data-slot="input"][type="date"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'inv-add-submit',
        title: 'Submitting the Form',
        description: 'Review the profit analysis showing your margins. When ready, click "Commit Ledger" to save the item to inventory.',
        instruction: 'Check the base and pack profit margins displayed. If satisfied, click "Commit Ledger" to save. Click "Abort" to cancel.',
        targetSelector: 'button[type="submit"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      // ── Purchase Order Form ──
      {
        id: 'inv-po-open',
        title: 'Creating a Purchase Order',
        description: 'Purchase Orders help you restock inventory. Search for items, set order quantities, and generate reports.',
        instruction: 'Click the Purchase Order button (Shopping Cart icon) to open the PO form.',
        targetSelector: 'button:has(svg.lucide-shopping-cart)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'inv-po-search',
        title: 'Adding Items to PO',
        description: 'Search for products to add to your purchase order. You can also add custom items not yet in inventory.',
        instruction: 'Type a product name in the search box, then click "+ Add" next to items. For custom items, fill in the name, quantity, and price fields at the bottom.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'inv-po-submit',
        title: 'Finalizing the PO',
        description: 'Review all items and their quantities. The estimated total cost is displayed. Submit to create the purchase order.',
        instruction: 'Adjust quantities as needed. Click "Generate Purchase Order" to create the PO and optionally print it.',
        targetSelector: 'button[type="submit"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'inv-restock',
        title: 'Restocking Items',
        description: 'When stock runs low, restock directly from the inventory list. This updates quantities and records purchase history.',
        instruction: 'Find an item row and click the restock icon (refresh arrows). Enter the additional quantity and the new purchase price.',
        targetSelector: 'button:has(svg.lucide-rotate-ccw)',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'inv-best-practices',
        title: 'Best Practices',
        description: 'Keep your inventory accurate with these tips.',
        instruction: '• Set reorder alerts for fast-moving items\n• Use categories to organize products\n• Update purchase prices when restocking\n• Run stock counts regularly\n• Export reports weekly for backup',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // SALES — 3-step wizard (search → review → settlement + payment)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-sales',
    screenPath: '/sales',
    screenName: 'Sales',
    title: 'Sales Management',
    description: 'Learn how to record sales, manage transactions, handle returns, and track sales performance.',
    estimatedDuration: 12,
    steps: [
      {
        id: 'sales-welcome',
        title: 'Recording Sales',
        description: 'The Sales screen lets you record every transaction. You can add items, apply discounts, track payments, and generate receipts.',
        instruction: 'The main table shows your sales history. Each row is a complete transaction with date, customer, items, and total.',
        targetSelector: 'div.overflow-auto.rounded-xl.border',
        tooltipPosition: 'bottom',
      },
      {
        id: 'sales-new',
        title: 'Starting a New Sale',
        description: 'Click "New Sale" to open the 3-step transaction wizard: Selection → Review → Settlement.',
        instruction: 'Click the "New Sale" button to begin. The wizard guides you through each step.',
        targetSelector: 'button:has(svg.lucide-plus)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'sales-step1',
        title: 'Step 1: Selecting Items',
        description: 'Search for inventory items and add them to the cart. The search filters in real time as you type.',
        instruction: 'Type an item name in the search box. Results appear instantly. Click on an item to add it to the cart with default quantity 1.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'sales-step1-review',
        title: 'Reviewing Your Cart',
        description: 'The cart badge shows how many items you\'ve selected. Click "Review Ledger" when done to proceed to Step 2.',
        instruction: 'Review the cart badge showing item count. Click "Review Ledger (N)" to proceed, or "Save Draft" to continue later.',
        targetSelector: 'button[type="submit"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'sales-step2-qty',
        title: 'Step 2: Adjust Quantities & Units',
        description: 'In the review step, you can adjust quantities using +/- buttons, change unit type (individual vs pack), or remove items.',
        instruction: 'Use the + and - buttons to adjust quantities. Use the dropdown to switch between base unit and pack unit for each item.',
        targetSelector: 'button:has(svg.lucide-plus)',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'sales-step2-proceed',
        title: 'Proceeding to Settlement',
        description: 'Once the cart looks right, click "Proceed Settlement" to enter payment details and customer info.',
        instruction: 'Click "Add More" to go back and add items, "Save Draft" to save for later, or "Proceed Settlement" to continue.',
        targetSelector: 'button:has(svg.lucide-arrow-right)',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'sales-step3-discount',
        title: 'Step 3: Discount & VAT',
        description: 'Enter a flat discount amount and VAT percentage. These are applied to the subtotal before calculating the final total.',
        instruction: 'Enter a discount in ETB (e.g. 50 for a 50 Birr discount). Enter VAT percentage (e.g. 15 for 15%). Leave as 0 if not applicable.',
        targetSelector: 'input[data-slot="input"][type="number"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'sales-step3-customer',
        title: 'Customer Information',
        description: 'Enter the customer name and phone number. For credit sales, this information is required to track the debt.',
        instruction: 'Type the customer\'s name and phone. If this is a walk-in sale, you can leave these blank for cash settlements.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'sales-step3-payment',
        title: 'Payment Method',
        description: 'Choose how the customer pays: Cash, Bank Transfer, Check, or Other. Toggle between cash settlement and credit (debt) sale.',
        instruction: 'Select a payment method. Toggle to "Debt" if the customer will pay later — a due date field will appear.',
        targetSelector: 'button[data-slot="switch"][role="switch"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'sales-step3-submit',
        title: 'Completing the Sale',
        description: 'Review the final total in the highlighted summary card. Click "Authorize" to complete the transaction.',
        instruction: 'Verify the total is correct. Check the settlement summary. Click "Authorize" to finalize. A receipt will be generated.',
        targetSelector: 'button:has(svg.lucide-check)',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'sales-return',
        title: 'Processing a Return',
        description: 'If a customer needs to return an item, use the return form. Enter the quantity to return and refund amount.',
        instruction: 'Click the return icon on any sale. Enter the quantity to return (max: original quantity). Set refund to 0 for exchange only. Provide a reason.',
        targetSelector: 'button:has(svg.lucide-undo-2)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'sales-detail-edit',
        title: 'Editing a Transaction (Sale Detail)',
        description: 'From the sale detail view, you can edit the customer info, quantity, discount, and VAT for any transaction.',
        instruction: 'Click the edit icon on a sale. Update the customer name, phone, quantity, discount, or VAT fields. Click Confirm to save changes.',
        tooltipPosition: 'center',
      },
      {
        id: 'sales-best-practices',
        title: 'Sales Best Practices',
        description: 'Master these tips for accurate sales tracking.',
        instruction: '• Always verify quantities before completing a sale\n• Use credit sales sparingly and track debts\n• Generate receipts for every transaction\n• Reconcile daily sales with cash on hand\n• Review sales trends weekly to spot patterns',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // EXPENSES — Add Expense form + Set Budget form
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-expenses',
    screenPath: '/expenses',
    screenName: 'Expenses',
    title: 'Expense Tracking',
    description: 'Learn how to record and categorize business expenses, set budgets, and track spending patterns.',
    estimatedDuration: 10,
    steps: [
      {
        id: 'expenses-welcome',
        title: 'Tracking Business Expenses',
        description: 'The Expenses screen helps you record every business expense. Proper expense tracking is essential for accurate profit calculation.',
        instruction: 'The table shows your recorded expenses. Each entry includes the amount, category, date, and payment method.',
        targetSelector: 'div.overflow-auto.rounded-xl.border',
        tooltipPosition: 'bottom',
      },
      // ── Add Expense Form ──
      {
        id: 'expenses-add-open',
        title: 'Opening the Add Expense Form',
        description: 'Click the + button or "Add Expense" to open the expense form. You\'ll enter the description, amount, category, and date.',
        instruction: 'Click the large + button to begin recording a new expense.',
        targetSelector: 'button:has(svg.lucide-plus)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'expenses-add-name',
        title: 'Expense Description (Required)',
        description: 'Enter a clear description of the expense. This helps identify the transaction when reviewing reports.',
        instruction: 'Type a descriptive name, e.g. "Office Rent — July" or "Electricity Bill — June". Be specific for easier tracking.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'expenses-add-amount',
        title: 'Expense Amount',
        description: 'Enter the total amount paid for this expense. All amounts are in your business currency (ETB by default).',
        instruction: 'Enter the exact amount paid. Double-check receipts for accuracy.',
        targetSelector: 'input[data-slot="input"][type="number"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'expenses-add-category',
        title: 'Selecting a Category',
        description: 'Categories organize your expenses for reporting. Choose the most specific category for each expense.',
        instruction: 'Select a category that best matches the expense type — Rent, Utilities, Supplies, Salaries, Transport, etc.',
        targetSelector: 'button[data-slot="select-trigger"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'expenses-add-date',
        title: 'Transaction Date',
        description: 'Set the date when the expense occurred. This affects which period the expense appears in for reporting.',
        instruction: 'Pick the date from the date picker. Defaults to today. Use the actual transaction date, not when you\'re entering it.',
        targetSelector: 'input[data-slot="input"][type="date"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'expenses-add-recurring',
        title: 'Recurring Expenses',
        description: 'For regular expenses like rent or subscriptions, enable the recurring toggle. Set the frequency and next billing date.',
        instruction: 'Toggle "Recurring" on. Choose frequency (Daily, Weekly, Monthly). Set start date and next billing date for automatic reminders.',
        targetSelector: 'button[data-slot="switch"][role="switch"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'expenses-add-submit',
        title: 'Committing the Expense',
        description: 'Review the details and click "Commit" to save. The expense will appear in your records and reports immediately.',
        instruction: 'Verify all fields are correct. Click "Commit" to record the expense. Click "Abort" to discard changes.',
        targetSelector: 'button[type="submit"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      // ── Budget Form ──
      {
        id: 'expenses-budget-open',
        title: 'Setting a Budget',
        description: 'Switch to the Budget tab to set spending limits. Budgets help you control costs and plan ahead.',
        instruction: 'Click the "Budgets" tab, then click "Set Budget" to open the form.',
        targetSelector: 'button:has(svg.lucide-wallet)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'expenses-budget-category',
        title: 'Budget Category',
        description: 'Select the expense category this budget applies to. Each category can have its own monthly or yearly limit.',
        instruction: 'Choose a category from the dropdown, e.g. "Utilities" or "Supplies".',
        targetSelector: 'button[data-slot="select-trigger"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'expenses-budget-amount',
        title: 'Budget Amount',
        description: 'Enter the maximum amount you plan to spend in this category for the selected period.',
        instruction: 'Set a realistic limit. Check previous spending to set an appropriate budget. Enter the amount in ETB.',
        targetSelector: 'input[data-slot="input"][type="number"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'expenses-budget-period',
        title: 'Budget Period',
        description: 'Choose how often the budget resets: monthly, quarterly, or yearly.',
        instruction: 'Select "Monthly" for regular monitoring, "Quarterly" for flexible tracking, or "Yearly" for annual planning.',
        targetSelector: 'button[data-slot="select-trigger"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'expenses-budget-submit',
        title: 'Saving the Budget',
        description: 'Click "Save Budget" to set your spending limit. The budget dashboard will track actual spending against this target.',
        instruction: 'Review the budget details. Click "Save Budget" to activate the spending limit.',
        targetSelector: 'button[type="submit"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'expenses-best-practices',
        title: 'Expense Best Practices',
        description: 'Follow these guidelines for accurate expense tracking.',
        instruction: '• Record expenses immediately — don\'t wait until month-end\n• Use the description field to add context\n• Keep digital copies of receipts\n• Review expenses weekly against budget\n• Categorize consistently for accurate reports',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CUSTOMERS — Add/Edit Customer form + Payment form
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-customers',
    screenPath: '/customers',
    screenName: 'Customers',
    title: 'Customer Management',
    description: 'Learn how to manage customer records, track debts, and maintain contact information.',
    estimatedDuration: 10,
    steps: [
      {
        id: 'customers-welcome',
        title: 'Managing Customers',
        description: 'The Customers screen stores all customer information including contact details, debt balances, and purchase history.',
        instruction: 'The customer table shows names, phone numbers, outstanding balances, and total purchases.',
        targetSelector: 'div.overflow-auto.rounded-xl.border',
        tooltipPosition: 'bottom',
      },
      // ── Customer Form ──
      {
        id: 'customers-add-open',
        title: 'Opening the Add Customer Form',
        description: 'Click "Add Customer" to create a new record. The form has fields for all customer details.',
        instruction: 'Click "Add Customer" to open the form. Fields marked with * are required.',
        targetSelector: 'button:has(svg.lucide-plus)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'customers-add-name',
        title: 'Customer Name (Required)',
        description: 'Enter the customer\'s full name. This is how they\'ll appear in sales, debt records, and search results.',
        instruction: 'Type the customer\'s full name, e.g. "Abebe Kebede". Use a consistent naming convention.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'customers-add-group',
        title: 'Customer Group',
        description: 'Assign the customer to a group like Retail, Wholesale, or Premium. Groups help with targeted marketing and pricing.',
        instruction: 'Select a group from the dropdown. Choose "Retail" for individual buyers, "Wholesale" for bulk purchasers.',
        targetSelector: 'button[data-slot="select-trigger"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'customers-add-phone',
        title: 'Phone & Contact Info',
        description: 'Enter the customer\'s primary phone number. This is used for debt follow-ups and communication.',
        instruction: 'Enter phone number with area code, e.g. "+251911123456". Add secondary phone, email, and company details as needed.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'customers-add-credit',
        title: 'Credit Limit',
        description: 'Set a credit limit for this customer. This controls how much they can owe before requiring payment.',
        instruction: 'Enter the maximum credit amount in ETB. Set to 0 if you don\'t want to extend credit. Be conservative — it\'s easier to increase later.',
        targetSelector: 'input[data-slot="input"][type="number"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'customers-add-location',
        title: 'City & Address',
        description: 'Record the customer\'s location. This is useful for delivery routing and market analysis.',
        instruction: 'Enter the city, e.g. "Addis Ababa". Add a specific address for delivery purposes.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'customers-add-submit',
        title: 'Saving the Customer',
        description: 'Review all fields and click "Create Customer" to save. The customer will immediately be available for sales and debt tracking.',
        instruction: 'Add optional notes if needed. Click "Create Customer" to save, or "Cancel" to discard.',
        targetSelector: 'button[type="submit"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      // ── Payment Form ──
      {
        id: 'customers-payment',
        title: 'Recording a Customer Payment',
        description: 'When a customer pays off a debt, use the payment form. Enter the amount and confirm.',
        instruction: 'From the customer profile, click "Pay" on a debt entry. Enter the payment amount (max: outstanding balance). Click "Confirm Payment".',
        targetSelector: 'button:has(svg.lucide-credit-card)',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'customers-best-practices',
        title: 'Customer Best Practices',
        description: 'Keep your customer relationships strong.',
        instruction: '• Always verify customer identity for credit sales\n• Follow up on overdue debts promptly but professionally\n• Keep contact information up to date\n• Use the notes field for important customer preferences\n• Review customer purchase history before offering credit',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // ANALYTICS
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-analytics',
    screenPath: '/analytics',
    screenName: 'Analytics',
    title: 'Business Analytics',
    description: 'Learn how to analyze your business performance using charts, reports, and data visualizations.',
    estimatedDuration: 5,
    steps: [
      {
        id: 'analytics-welcome',
        title: 'Understanding Your Analytics',
        description: 'The Analytics screen provides detailed visualizations of your business data, helping you identify trends and opportunities.',
        instruction: 'Analytics are organized by category: sales, expenses, inventory, and customers. Each section offers different chart types.',
        tooltipPosition: 'center',
      },
      {
        id: 'analytics-sales',
        title: 'Sales Analytics',
        description: 'View sales trends over time with interactive charts. Compare periods, identify peak seasons, and track growth.',
        instruction: 'Switch between chart views (bar, line, area) to find the visualization that makes trends clearest to you.',
        targetSelector: 'svg.recharts-surface',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'analytics-period',
        title: 'Selecting Time Periods',
        description: 'Choose different time ranges to analyze: daily, weekly, monthly, quarterly, or custom date ranges.',
        instruction: 'Try changing the period selector. Compare this month to last month to see growth or decline.',
        targetSelector: 'div.flex.bg-muted.p-1.rounded-xl',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'analytics-export',
        title: 'Exporting Reports',
        description: 'Export analytics data and charts to PDF or CSV for presentations, meetings, and record-keeping.',
        instruction: 'Click the export button to download the current view as a report. You can include charts and data tables.',
        tooltipPosition: 'center',
      },
      {
        id: 'analytics-best-practices',
        title: 'Analytics Best Practices',
        description: 'Get the most value from your analytics.',
        instruction: '• Review analytics weekly, not just monthly\n• Compare against previous periods for context\n• Export monthly reports for your records\n• Use filters to isolate specific products or categories\n• Share insights with your team during meetings',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // SETTINGS
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-settings',
    screenPath: '/settings',
    screenName: 'Settings',
    title: 'App Settings',
    description: 'Learn how to configure the application, manage your business profile, set preferences, and customize themes.',
    estimatedDuration: 4,
    steps: [
      {
        id: 'settings-welcome',
        title: 'Configuring Your App',
        description: 'The Settings screen lets you customize every aspect of the application, from language and theme to business information and module preferences.',
        instruction: 'Settings are organized into tabs: Appearance, Language, Business, and Modules. Navigate between them to explore options.',
        targetSelector: 'div[data-slot="tabs-list"]',
        tooltipPosition: 'bottom',
      },
      {
        id: 'settings-theme',
        title: 'Choosing a Theme',
        description: 'Switch between Light, Dark, and five custom themes. The interface updates in real time.',
        instruction: 'Click different theme options to see how they change the interface. Each theme is designed for comfortable extended use.',
        targetSelector: 'div.grid.grid-cols-4.gap-3',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'settings-language',
        title: 'Changing Language',
        description: 'The app supports English, Amharic, Oromo, and Tigrinya. Switch languages at any time.',
        instruction: 'Click the Language tab and select a different language to see the interface update. All menus and labels will change.',
        targetSelector: 'button[data-slot="tabs-trigger"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'settings-business',
        title: 'Business Information',
        description: 'Update your business name, currency, and other settings. These values are used throughout the app.',
        instruction: 'Review the business information and ensure your currency setting matches your local currency for accurate financial reporting.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'left',
      },
      {
        id: 'settings-best-practices',
        title: 'Settings Best Practices',
        description: 'Optimize your setup with these recommendations.',
        instruction: '• Choose a theme that reduces eye strain during long sessions\n• Set the correct currency before recording any transactions\n• Enable only the modules you actively use\n• Review settings periodically as your business grows',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // WAREHOUSES — Add, Transfer Stock, Adjust Qty forms
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-warehouses',
    screenPath: '/warehouses',
    screenName: 'Warehouses',
    title: 'Warehouse Management',
    description: 'Learn how to manage multiple warehouses, track stock across locations, and organize inventory by storage area.',
    estimatedDuration: 8,
    steps: [
      {
        id: 'warehouses-welcome',
        title: 'Managing Warehouses',
        description: 'The Warehouses screen lets you organize inventory across multiple physical storage locations.',
        instruction: 'View all warehouses, their locations, and stock counts. Use this to manage inventory spread across different sites.',
        targetSelector: 'div[data-slot="card"]',
        tooltipPosition: 'bottom',
      },
      // ── Add Warehouse Form ──
      {
        id: 'warehouses-add-open',
        title: 'Adding a Warehouse',
        description: 'Create new warehouse records with names, locations, manager information, and contact details.',
        instruction: 'Click "Add Warehouse" to open the form. We\'ll walk through each field.',
        targetSelector: 'button:has(svg.lucide-plus)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'warehouses-add-name',
        title: 'Warehouse Name (Required)',
        description: 'Enter a descriptive name for the warehouse. Use names that make location and purpose clear.',
        instruction: 'Type a name like "Main Warehouse — Bole" or "Cold Storage — Kality". Be specific enough to distinguish from other warehouses.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'warehouses-add-location',
        title: 'Warehouse Location',
        description: 'Enter the physical location or address of the warehouse for reference.',
        instruction: 'Type the location, e.g. "Bole, Addis Ababa" or "Headquarters Building, 2nd Floor".',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'warehouses-add-manager',
        title: 'Manager Details',
        description: 'Assign a manager to the warehouse. Include their name, phone number, and email for contact purposes.',
        instruction: 'Enter the manager\'s name, phone number with area code, and email address. This helps with coordination.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'warehouses-add-submit',
        title: 'Saving the Warehouse',
        description: 'Review the details and click "Create Warehouse" to save the new location.',
        instruction: 'Click "Create Warehouse" to save. The warehouse will appear in the list and be available for stock transfers.',
        targetSelector: 'button:has(svg.lucide-check)',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      // ── Transfer Stock Form ──
      {
        id: 'warehouses-transfer-open',
        title: 'Transferring Stock Between Warehouses',
        description: 'Move inventory from one warehouse to another. Select source, destination, item, and quantity.',
        instruction: 'Click the "Transfer Stock" button to open the form.',
        targetSelector: 'button:has(svg.lucide-arrow-right-left)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'warehouses-transfer-source',
        title: 'Select Source & Destination',
        description: 'Choose which warehouse the stock is leaving and which one it\'s going to. They must be different.',
        instruction: 'Select the source warehouse (where stock is now) and destination warehouse (where stock is going). Cannot be the same.',
        targetSelector: 'button[data-slot="select-trigger"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'warehouses-transfer-item',
        title: 'Select Item & Quantity',
        description: 'Choose the item to transfer and enter the quantity. The system checks available stock at the source.',
        instruction: 'Select an item from the dropdown. Enter the quantity to transfer. Add the name of the person authorizing the transfer.',
        targetSelector: 'input[data-slot="input"][type="number"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'warehouses-transfer-submit',
        title: 'Executing the Transfer',
        description: 'Review the transfer details and click "Execute Transfer". Stock counts update immediately at both locations.',
        instruction: 'Add optional notes. Click "Execute Transfer" to complete. You can view the transfer history in the warehouse details.',
        targetSelector: 'button[type="submit"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'warehouses-adjust-open',
        title: 'Adjusting Inventory Quantities',
        description: 'Set exact inventory quantities for a specific item in a warehouse. Use this for stock counts and corrections.',
        instruction: 'Click the "Set Inventory Qty" button. Select warehouse, item, and enter the new quantity.',
        targetSelector: 'button:has(svg.lucide-pencil)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'warehouses-best-practices',
        title: 'Warehouse Best Practices',
        description: 'Keep your warehouses organized.',
        instruction: '• Assign a responsible person to each warehouse\n• Conduct monthly stock counts\n• Use transfers to document all movement\n• Keep warehouse names descriptive (e.g. "Main Store — Ground Floor")\n• Review warehouse activity weekly',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // ADJUSTMENTS — Inline stock/price/bulk forms
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-adjustments',
    screenPath: '/adjustments',
    screenName: 'Adjustments',
    title: 'Stock Adjustments',
    description: 'Learn how to record inventory adjustments for damaged goods, returns, and stock corrections.',
    estimatedDuration: 8,
    steps: [
      {
        id: 'adjustments-welcome',
        title: 'Recording Adjustments',
        description: 'Stock adjustments correct inventory records when actual count differs from system count.',
        instruction: 'Use the tabs to switch between Stock, Price, and Bulk adjustment forms. The History tab shows past adjustments.',
        targetSelector: 'div[data-slot="tabs-list"]',
        tooltipPosition: 'bottom',
      },
      // ── Stock Adjustment Form ──
      {
        id: 'adjustments-stock-type',
        title: 'Stock Adjustment — Action Type',
        description: 'Choose what type of stock change you\'re recording: add stock, damage, or loss.',
        instruction: 'Select the type: "Add Stock" for new inventory, "Damage" for damaged goods, or "Loss" for missing items.',
        targetSelector: 'button[data-slot="select-trigger"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'adjustments-stock-item',
        title: 'Select the Item & Quantity',
        description: 'Choose the product being adjusted and enter the quantity affected.',
        instruction: 'Select an item from the dropdown. Enter the quantity (use positive numbers for additions, the system handles the direction).',
        targetSelector: 'input[data-slot="input"][type="number"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'adjustments-stock-reason',
        title: 'Provide a Reason',
        description: 'Always document why the adjustment is needed. This is critical for audits and inventory accuracy.',
        instruction: 'Type a clear reason like "5 cartons damaged during transport" or "10 units found during stock count". Be specific.',
        targetSelector: 'textarea',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'adjustments-stock-submit',
        title: 'Applying the Adjustment',
        description: 'Review the impact preview showing current vs. new stock levels. Click "Submit Adjustment" to apply.',
        instruction: 'Check the impact preview for financial implications. Click "Submit Adjustment" to record the change.',
        targetSelector: 'button[type="submit"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      // ── Price Adjustment Form ──
      {
        id: 'adjustments-price-tab',
        title: 'Price Adjustments',
        description: 'Switch to the Price tab to update item selling prices. Select item, unit type, and enter the new price.',
        instruction: 'Click the "Price" tab. Select the item and unit type (base or pack). Enter the new selling price and an optional reason.',
        targetSelector: 'button[data-slot="tabs-trigger"]',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      // ── Bulk Adjustment Form ──
      {
        id: 'adjustments-bulk-tab',
        title: 'Bulk Adjustments',
        description: 'The Bulk tab lets you adjust prices for entire categories at once — percentage increase or fixed amount changes.',
        instruction: 'Click the "Bulk" tab. Select a category (or "All Items"), choose adjustment type (percentage or fixed), and enter the value.',
        targetSelector: 'button[data-slot="tabs-trigger"]',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'adjustments-best-practices',
        title: 'Adjustment Best Practices',
        description: 'Follow these guidelines for accurate adjustments.',
        instruction: '• Always investigate discrepancies before adjusting\n• Document the reason clearly\n• Get manager approval for significant adjustments\n• Review adjustment reports monthly for patterns\n• Use bulk adjustments carefully — verify impact first',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // DEBT MANAGEMENT — Payment form + Reverse Payment
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-debt-management',
    screenPath: '/debt-management',
    screenName: 'Debt Management',
    title: 'Debt Management',
    description: 'Learn how to track customer debts, record payments, and manage collections.',
    estimatedDuration: 7,
    steps: [
      {
        id: 'debt-welcome',
        title: 'Managing Customer Debts',
        description: 'The Debt Management screen provides a comprehensive view of all customer debts, payment history, and collection tools.',
        instruction: 'View all outstanding debts at a glance. The table shows customer names, amounts owed, due dates, and aging.',
        targetSelector: 'div.overflow-auto.rounded-xl.border',
        tooltipPosition: 'bottom',
      },
      {
        id: 'debt-filter',
        title: 'Filtering Debts',
        description: 'Use filters to narrow down by date range. This helps focus on specific periods.',
        instruction: 'Click the Filter button and set a date range to view debts from a specific period.',
        targetSelector: 'button:has(svg.lucide-list-filter)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      // ── Payment Form ──
      {
        id: 'debt-payment-open',
        title: 'Recording a Payment',
        description: 'When a customer pays, click the ellipsis menu on their debt row and select "Mark as Paid".',
        instruction: 'Click the three-dot menu on a debt row, then select "Mark as Paid" to open the payment form.',
        targetSelector: 'button:has(svg.lucide-more-horizontal)',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'debt-payment-amount',
        title: 'Payment Amount',
        description: 'Enter how much the customer is paying. The max amount shown is their outstanding balance.',
        instruction: 'Type the payment amount. You can pay partially — the remaining balance stays on the debt. Enter any amount up to the max shown.',
        targetSelector: 'input[data-slot="input"][type="number"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'debt-payment-method',
        title: 'Payment Method',
        description: 'Select how the customer paid: Cash, Bank Transfer, Mobile Money, or Check.',
        instruction: 'Choose the payment method that matches how the customer actually paid.',
        targetSelector: 'button[data-slot="select-trigger"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'debt-payment-note',
        title: 'Payment Note (Optional)',
        description: 'Add a note about the payment for reference, like receipt number or any special terms.',
        instruction: 'Optionally add a note like "Receipt #12345" or "Paid via Bank of Abyssinia".',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'debt-payment-submit',
        title: 'Confirming the Payment',
        description: 'Click "Confirm Payment" to record it. The debt balance updates immediately.',
        instruction: 'Review the details. Click "Confirm Payment" to apply. The debt status will update to reflect the payment.',
        targetSelector: 'button[type="submit"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'debt-reverse',
        title: 'Reversing a Payment',
        description: 'If a payment was recorded by mistake, you can reverse it. Click the undo icon on the payment history entry.',
        instruction: 'In the payment history, click the ban icon on an entry. Provide a reason for the reversal. This creates an audit trail.',
        targetSelector: 'button:has(svg.lucide-ban)',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'debt-best-practices',
        title: 'Debt Management Best Practices',
        description: 'Keep your receivables healthy.',
        instruction: '• Set clear credit terms before extending credit\n• Follow up on overdue debts within 7 days\n• Offer receipts for every payment\n• Review the debt report weekly\n• Consider setting credit limits for customers',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // ORDERS — Create Order form + Convert modals
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-orders',
    screenPath: '/orders',
    screenName: 'Orders',
    title: 'Order Management',
    description: 'Learn how to manage customer orders from creation to fulfillment, including conversion to sales or debts.',
    estimatedDuration: 8,
    steps: [
      {
        id: 'orders-welcome',
        title: 'Managing Orders',
        description: 'The Orders screen tracks customer orders through their lifecycle: pending, confirmed, shipped, and delivered.',
        instruction: 'The order table shows all orders with their current status. Use the status column to see which orders need attention.',
        targetSelector: 'div.overflow-auto.rounded-xl.border',
        tooltipPosition: 'bottom',
      },
      // ── Create Order Form ──
      {
        id: 'orders-create-open',
        title: 'Creating a New Order',
        description: 'Click "New Order" to open the order creation form. Enter customer details and add items.',
        instruction: 'Click "New Order" to begin. We\'ll walk through the form fields together.',
        targetSelector: 'button:has(svg.lucide-plus)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'orders-create-customer',
        title: 'Customer Information',
        description: 'Enter the customer name and phone number. This links the order to the customer for tracking.',
        instruction: 'Type the customer\'s name and phone. These help identify the order throughout its lifecycle.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'orders-create-notes',
        title: 'Order Notes',
        description: 'Add any special instructions or notes about the order, like delivery preferences or special requests.',
        instruction: 'Type notes like "Deliver after 5 PM" or "Call before delivery". This field is optional but helpful.',
        targetSelector: 'textarea',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'orders-create-items',
        title: 'Adding Items to the Order',
        description: 'Search for inventory items, adjust quantities and prices, and build the order cart.',
        instruction: 'Type to search items. Click on an item to add it. Adjust quantity and unit price for each cart item.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'orders-create-submit',
        title: 'Creating the Order',
        description: 'Review the cart total and click "Create Order" to save. The order will appear with "Pending" status.',
        instruction: 'Verify the items and total. Click "Create Order" to finalize. You can convert it to a sale or debt later.',
        targetSelector: 'button[type="submit"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      // ── Convert to Sale ──
      {
        id: 'orders-convert-sale',
        title: 'Converting an Order to Sale',
        description: 'When the customer is ready, convert the order to a sale. Select the payment method to complete the transaction.',
        instruction: 'Click "Convert to Sale" on an order. Choose the payment method (Cash, Bank Transfer, etc.). Click "Confirm Convert".',
        targetSelector: 'button:has(svg.lucide-receipt)',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'orders-convert-debt',
        title: 'Converting an Order to Debt',
        description: 'If the customer wants credit, convert the order to a debt. Set the due date for payment follow-up.',
        instruction: 'Click "Convert to Debt". Set the due date by which the customer should pay. Click "Confirm Convert".',
        targetSelector: 'button:has(svg.lucide-credit-card)',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'orders-best-practices',
        title: 'Order Best Practices',
        description: 'Keep orders organized and customers happy.',
        instruction: '• Update order status promptly to keep customers informed\n• Verify stock availability before confirming orders\n• Keep delivery notes for reference\n• Review pending orders daily\n• Convert orders to sales or debts as soon as possible',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // EMPLOYEES — Employee, Role, Account forms
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-employees',
    screenPath: '/employees',
    screenName: 'Employees',
    title: 'Employee Management',
    description: 'Learn how to manage employee records, assign roles, and create system accounts.',
    estimatedDuration: 10,
    steps: [
      {
        id: 'employees-welcome',
        title: 'Managing Employees',
        description: 'The Employee Management screen helps you track your team members, their roles, and contact information.',
        instruction: 'The employee table shows names, positions, phone numbers, and departments.',
        targetSelector: 'div.rounded-2xl.border.bg-card\\/40.overflow-hidden',
        tooltipPosition: 'bottom',
      },
      // ── Employee Form ──
      {
        id: 'employees-add-open',
        title: 'Adding an Employee',
        description: 'Click "Add Employee" to open the form. Enter personal details, contact info, role, and employment status.',
        instruction: 'Click "Add Employee" to begin. Fields marked with * are required.',
        targetSelector: 'button:has(svg.lucide-user-plus)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'employees-add-name',
        title: 'Employee Name (Required)',
        description: 'Enter the employee\'s first and last name. These are used in reports and system access.',
        instruction: 'Type the first name and last name. Example: First Name: "John", Last Name: "Doe".',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'employees-add-code',
        title: 'Employee Code & Role',
        description: 'Assign a unique employee code (like EMP-001) and select their role from the dropdown.',
        instruction: 'Enter an employee code for identification. Select a role that matches their job function (e.g. Cashier, Manager).',
        targetSelector: 'select',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'employees-add-contact',
        title: 'Contact Information',
        description: 'Enter the employee\'s phone number and email for communication and emergency contact.',
        instruction: 'Enter phone number with area code. Enter email address for official communications.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'employees-add-hire-date',
        title: 'Hire Date',
        description: 'Record when the employee started working. This is used for tenure tracking and reports.',
        instruction: 'Select the hire date from the date picker. Defaults to today if not set.',
        targetSelector: 'input[data-slot="input"][type="date"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'employees-add-submit',
        title: 'Saving the Employee',
        description: 'Click "Create" to save the employee record. They\'ll appear in the employee list.',
        instruction: 'Review all fields. Click "Create" to save the employee.',
        targetSelector: 'button[data-slot="button"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      // ── Role Form ──
      {
        id: 'employees-role-open',
        title: 'Creating a Role',
        description: 'Roles define what permissions an employee has. Create roles like "Cashier" or "Manager" with specific access.',
        instruction: 'Click "Add Role". Enter the role name, description, and select permissions for this role.',
        targetSelector: 'button:has(svg.lucide-plus)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'employees-role-permissions',
        title: 'Setting Permissions',
        description: 'Check the permissions this role should have. Each permission controls access to a specific feature.',
        instruction: 'Select permissions by checking the boxes. Be thoughtful — give only the access needed for the job.',
        targetSelector: 'input[type="checkbox"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'employees-role-submit',
        title: 'Saving the Role',
        description: 'Click "Create" to save the role. It will be available when adding or editing employees.',
        instruction: 'Verify the permissions are correct. Click "Create" to save.',
        targetSelector: 'button[data-slot="button"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      // ── Account Form ──
      {
        id: 'employees-account-open',
        title: 'Creating a System Account',
        description: 'System accounts let employees log in to the application. Select an employee and set their username and PIN.',
        instruction: 'Click "Add Account". Select the employee from the dropdown. This creates their login credentials.',
        targetSelector: 'button:has(svg.lucide-key-round)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'employees-account-credentials',
        title: 'Username & PIN',
        description: 'Set the login username and a numeric PIN. The PIN is used for quick access. Optionally force a password change on next login.',
        instruction: 'Enter a unique username (e.g. johndoe). Set a 4-digit PIN. Check "Force password change" if this is a first-time user.',
        targetSelector: 'input[data-slot="input"][type="password"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'employees-account-submit',
        title: 'Creating the Account',
        description: 'Click "Create Account" to finalize. The employee can now log in with their credentials.',
        instruction: 'Click "Create Account" to save. Share the credentials with the employee securely.',
        targetSelector: 'button[data-slot="button"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'employees-best-practices',
        title: 'Employee Best Practices',
        description: 'Keep your team organized.',
        instruction: '• Update employee records when roles change\n• Use strong PINs for all accounts\n• Review permissions quarterly\n• Remove accounts when employees leave\n• Keep emergency contact info current',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // SHIPMENTS — Create/Edit Shipment form
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-shipments',
    screenPath: '/shipments',
    screenName: 'Shipments',
    title: 'Shipment Tracking',
    description: 'Learn how to track incoming and outgoing shipments, manage carriers, and monitor delivery status.',
    estimatedDuration: 7,
    steps: [
      {
        id: 'shipments-welcome',
        title: 'Tracking Shipments',
        description: 'The Shipments screen helps you track goods coming in from suppliers and going out to customers.',
        instruction: 'View all shipments with their status, expected dates, and carrier information.',
        targetSelector: 'div.grid.grid-cols-1',
        tooltipPosition: 'bottom',
      },
      // ── Shipment Form ──
      {
        id: 'shipments-add-open',
        title: 'Creating a New Shipment',
        description: 'Click "New Shipment" to open the form. Enter origin, destination, driver, vehicle, and schedule details.',
        instruction: 'Click "New Shipment" to begin. We\'ll walk through each field.',
        targetSelector: 'button:has(svg.lucide-truck)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'shipments-add-route',
        title: 'Origin & Destination',
        description: 'Enter where the shipment is coming from and where it\'s going. Both fields help with route planning.',
        instruction: 'Type the origin (e.g. "Supplier Warehouse — Bole"). Enter the destination (e.g. "Main Store — Merkato"). Destination is required.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'shipments-add-driver',
        title: 'Driver & Vehicle Info',
        description: 'Record the driver\'s name, phone number, and vehicle details for tracking and communication.',
        instruction: 'Enter driver name, phone number with area code, and vehicle info (e.g. "Isuzu FRX — Plate: AA 12345").',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'shipments-add-schedule',
        title: 'Scheduled Date & Notes',
        description: 'Set the expected departure or arrival date. Add any special instructions for the driver or recipient.',
        instruction: 'Pick the scheduled date. Add notes like "Handle with care — fragile items" or "Deliver to loading dock B".',
        targetSelector: 'input[data-slot="input"][type="date"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'shipments-add-submit',
        title: 'Creating the Shipment',
        description: 'Click "Create" to save the shipment. It will appear with "Pending" status. You can update status as it progresses.',
        instruction: 'Review all details. Click "Create" to save. Use the "Mark In Transit" and "Mark Delivered" buttons to update status.',
        targetSelector: 'button:has(svg.lucide-check)',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'shipments-best-practices',
        title: 'Shipment Best Practices',
        description: 'Keep shipments organized.',
        instruction: '• Record shipments immediately when goods leave\n• Update status promptly as shipments progress\n• Keep driver contact info handy\n• Add detailed notes for special handling\n• Review pending shipments daily',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // SUPPLIERS — Payment form + Price Check form
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-suppliers',
    screenPath: '/suppliers',
    screenName: 'Suppliers',
    title: 'Supplier Management',
    description: 'Learn how to manage supplier information, record payments, and schedule price checks.',
    estimatedDuration: 8,
    steps: [
      {
        id: 'suppliers-welcome',
        title: 'Managing Suppliers',
        description: 'The Suppliers screen stores information about your vendors, including contact details, purchase history, and payment terms.',
        instruction: 'View all suppliers and their key information. Use this to manage your supply chain effectively.',
        targetSelector: 'div.overflow-auto.rounded-xl.border',
        tooltipPosition: 'bottom',
      },
      {
        id: 'suppliers-detail',
        title: 'Viewing Supplier Details',
        description: 'Click on a supplier to see their full profile including purchase history, payment records, and outstanding balances.',
        instruction: 'Click a supplier row to view details. This is useful before ordering or making payments.',
        targetSelector: 'button:has(svg.lucide-eye)',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      // ── Payment Form ──
      {
        id: 'suppliers-payment-open',
        title: 'Recording a Supplier Payment',
        description: 'When you pay a supplier, record the payment here. Select the purchase order, enter the amount, and choose the payment method.',
        instruction: 'Click "Record Payment" on a supplier\'s profile. We\'ll fill in the payment details.',
        targetSelector: 'button:has(svg.lucide-credit-card)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'suppliers-payment-date',
        title: 'Payment Date',
        description: 'Set the date the payment was made. This affects financial period reporting.',
        instruction: 'Select the actual payment date from the date picker.',
        targetSelector: 'input[data-slot="input"][type="date"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'suppliers-payment-amount',
        title: 'Payment Amount',
        description: 'Enter the amount paid. You can pay against a specific purchase order or as a general payment.',
        instruction: 'Type the amount. Select a specific purchase order to track which invoices are paid.',
        targetSelector: 'input[data-slot="input"][type="number"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'suppliers-payment-method',
        title: 'Payment Method & Reference',
        description: 'Select how the payment was made and enter a reference number for tracking.',
        instruction: 'Choose the method: Cash, Bank Transfer, Mobile Money, Check, or Other. Enter a reference number like the transaction ID.',
        targetSelector: 'select',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'suppliers-payment-submit',
        title: 'Saving the Payment',
        description: 'Click "Save" to record the payment. The supplier\'s balance updates immediately.',
        instruction: 'Add optional notes. Click "Save" to confirm the payment.',
        targetSelector: 'button[type="submit"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      // ── Price Check Form ──
      {
        id: 'suppliers-price-check',
        title: 'Scheduling a Price Check',
        description: 'Set up recurring price checks for suppliers. The system will remind you to verify and compare prices.',
        instruction: 'Click "Schedule Price Check". Select the supplier, optionally a specific item, frequency (weekly/biweekly/monthly), and add notes.',
        targetSelector: 'button:has(svg.lucide-bell)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'suppliers-best-practices',
        title: 'Supplier Best Practices',
        description: 'Build strong supplier relationships.',
        instruction: '• Maintain multiple suppliers for key items\n• Track supplier performance (on-time delivery, quality)\n• Keep payment terms and contact info current\n• Review supplier pricing periodically\n• Schedule regular price checks for competitive pricing',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // BUDGETS — Adjust Budget form
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-budgets',
    screenPath: '/budgets',
    screenName: 'Budgets',
    title: 'Budget Management',
    description: 'Learn how to set budgets for expense categories, track spending against targets, and make adjustments.',
    estimatedDuration: 5,
    steps: [
      {
        id: 'budgets-welcome',
        title: 'Setting Budgets',
        description: 'The Budget Management screen lets you set spending limits for each expense category and track actual spending against targets.',
        instruction: 'View your budget overview. Green indicates under budget, red means over budget.',
        targetSelector: 'div[data-slot="tabs-list"]',
        tooltipPosition: 'bottom',
      },
      {
        id: 'budgets-create',
        title: 'Creating a Budget',
        description: 'Set a budget for each category by entering a spending limit for a specific period.',
        instruction: 'Click "Set Budget". Choose a category, enter the amount, select the period. Be realistic — budgets should challenge but not restrict.',
        targetSelector: 'button:has(svg.lucide-plus)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'budgets-adjust',
        title: 'Adjusting a Budget',
        description: 'If actual spending differs from the budget, you can adjust the amount. Record the reason for the adjustment.',
        instruction: 'Click the adjust icon on a budget card. Enter the new amount (shows current budget as reference). Add a reason like "Increased rent" or "Seasonal adjustment".',
        targetSelector: 'button:has(svg.lucide-plus)',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'budgets-best-practices',
        title: 'Budget Best Practices',
        description: 'Stay on top of your finances.',
        instruction: '• Review budgets monthly and adjust as needed\n• Investigate categories that are consistently over budget\n• Set annual budgets and track monthly progress\n• Involve department heads in budget planning\n• Compare actual vs budgeted spending for insights',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CONTACTS — Add/Edit Contact form (Dialog)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-contacts',
    screenPath: '/contacts',
    screenName: 'Contacts',
    title: 'Contact Management',
    description: 'Learn how to manage business contacts including customers, suppliers, and other stakeholders.',
    estimatedDuration: 6,
    steps: [
      {
        id: 'contacts-welcome',
        title: 'Managing Contacts',
        description: 'The Contacts screen stores all your business contacts in one place, including customers, suppliers, and service providers.',
        instruction: 'Browse your contact list. Each contact shows name, phone number, and type (customer, supplier, etc.).',
        targetSelector: 'div.grid.gap-4',
        tooltipPosition: 'bottom',
      },
      // ── Contact Form ──
      {
        id: 'contacts-add-open',
        title: 'Adding a Contact',
        description: 'Click "Add Contact" to open the dialog form. Enter the contact\'s details.',
        instruction: 'Click "Add Contact" to begin. We\'ll walk through the form.',
        targetSelector: 'button:has(svg.lucide-plus)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'contacts-add-name',
        title: 'Contact Name (Required)',
        description: 'Enter the contact\'s full name. This is how they\'ll appear throughout the system.',
        instruction: 'Type the full name. Example: "Abebe Kebede" or "Shega Industries PLC".',
        targetSelector: 'input[required]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'contacts-add-phone',
        title: 'Phone Number (Required)',
        description: 'Enter the contact\'s phone number. This is the primary way to reach them.',
        instruction: 'Enter phone number with area code. Example: "+251911123456".',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'contacts-add-category',
        title: 'Category & Subcategory',
        description: 'Classify the contact by category (Customer, Supplier, Partner, etc.) and optionally a subcategory.',
        instruction: 'Select a category from the dropdown — this helps with filtering and organization. Add a subcategory for more detail, e.g. "Wholesale Buyer" or "Raw Materials Supplier".',
        targetSelector: 'button[data-slot="select-trigger"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'contacts-add-notes',
        title: 'Notes (Optional)',
        description: 'Add notes about the contact — preferences, special terms, or any relevant information.',
        instruction: 'Type any relevant notes. Example: "Prefers delivery on Tuesdays" or "Offers 30-day payment terms".',
        targetSelector: 'textarea[data-slot="textarea"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'contacts-add-submit',
        title: 'Saving the Contact',
        description: 'Review and click "Save" to add the contact to your list.',
        instruction: 'Verify the details. Click "Save" to create the contact. They\'ll immediately appear in the contact list.',
        targetSelector: 'button[type="submit"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'contacts-best-practices',
        title: 'Contact Best Practices',
        description: 'Keep your contact list valuable.',
        instruction: '• Update contact information regularly\n• Use the notes field for important details\n• Classify contacts correctly for better filtering\n• Remove or archive inactive contacts periodically\n• Export contacts as backup regularly',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // REPORTS
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-reports',
    screenPath: '/reports',
    screenName: 'Reports',
    title: 'Business Reports',
    description: 'Learn how to generate and export business reports for insights, analysis, and stakeholder communication.',
    estimatedDuration: 4,
    steps: [
      {
        id: 'reports-welcome',
        title: 'Generating Reports',
        description: 'The Reports screen lets you generate comprehensive business reports covering sales, expenses, inventory, and customer activities.',
        instruction: 'Choose from available report types. Each report provides a different perspective on your business performance.',
        targetSelector: 'div[data-slot="tabs-list"]',
        tooltipPosition: 'bottom',
      },
      {
        id: 'reports-generate',
        title: 'Creating a Report',
        description: 'Select the report type, set the date range, and generate your report. Data is presented in clear tables and charts.',
        instruction: 'Select a report type and date range, then click "Generate". Review the data before exporting.',
        targetSelector: 'button:has(svg.lucide-bar-chart-3)',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'reports-export',
        title: 'Exporting Reports',
        description: 'Export reports as PDF for presentations or CSV for data analysis in spreadsheet software.',
        instruction: 'Use the export buttons to download your report. PDF is best for sharing, CSV is best for further analysis.',
        targetSelector: 'button:has(svg.lucide-download)',
        tooltipPosition: 'left',
      },
      {
        id: 'reports-best-practices',
        title: 'Reports Best Practices',
        description: 'Get the most from your reports.',
        instruction: '• Generate monthly reports consistently\n• Compare reports month-over-month for trends\n• Export PDFs for management meetings\n• Use CSV exports for deep data analysis\n• Schedule regular report reviews',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // AUDIT LOGS
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-audit-logs',
    screenPath: '/audit-logs',
    screenName: 'Audit Logs',
    title: 'Audit Logs',
    description: 'Learn how to review system activity logs for security, compliance, and troubleshooting.',
    estimatedDuration: 3,
    steps: [
      {
        id: 'audit-welcome',
        title: 'Reviewing Audit Logs',
        description: 'Audit Logs track every action in the system — who did what and when. Use this for security monitoring and troubleshooting.',
        instruction: 'The log table shows actions with timestamps, user names, action types, and details.',
        targetSelector: 'div.rounded-2xl.border.bg-card\\/40.overflow-hidden',
        tooltipPosition: 'bottom',
      },
      {
        id: 'audit-filter',
        title: 'Filtering Audit Logs',
        description: 'Filter logs by date range, user, or action type to find specific events quickly.',
        instruction: 'Use filters to narrow down log entries. This is especially useful during investigations.',
        targetSelector: 'select',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'audit-best-practices',
        title: 'Audit Best Practices',
        description: 'Maintain good security practices.',
        instruction: '• Review audit logs weekly for unusual activity\n• Investigate failed login attempts\n• Keep logs for at least 90 days\n• Use filters to focus on critical actions\n• Export logs periodically for backup',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // REMINDERS — Reminder form
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-reminders',
    screenPath: '/reminders',
    screenName: 'Reminders',
    title: 'Reminder History',
    description: 'Learn how to view and manage system reminders including payment due dates, expiry alerts, and custom notifications.',
    estimatedDuration: 6,
    steps: [
      {
        id: 'reminders-welcome',
        title: 'Viewing Reminders',
        description: 'The Reminder History screen shows all system reminders, including payment due dates, expiry alerts, and other notifications.',
        instruction: 'Review past and upcoming reminders. Each reminder shows the type, date, and status.',
        targetSelector: 'div[data-slot="tabs-list"]',
        tooltipPosition: 'bottom',
      },
      // ── Reminder Form ──
      {
        id: 'reminders-add-open',
        title: 'Creating a Reminder',
        description: 'Click the + button to create a new reminder. Set the title, type, message, and trigger date/time.',
        instruction: 'Click the large + button to open the reminder form.',
        targetSelector: 'button:has(svg.lucide-plus)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'reminders-add-title',
        title: 'Reminder Title (Required)',
        description: 'Enter a clear title for the reminder. This is what you\'ll see in notifications and the reminder list.',
        instruction: 'Type a descriptive title like "Electricity Bill Due" or "Supplier Payment — ABC Corp". Be specific.',
        targetSelector: 'input[data-slot="input"][required]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'reminders-add-type',
        title: 'Reminder Type',
        description: 'Choose the type of reminder: payment, expiry, meeting, or custom. This helps with organization.',
        instruction: 'Select a type that best matches your reminder. Payment for bills, Expiry for deadlines, Meeting for appointments, Custom for anything else.',
        targetSelector: 'button[data-slot="select-trigger"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'reminders-add-message',
        title: 'Reminder Message',
        description: 'Write a detailed message that provides context and any action items for the reminder.',
        instruction: 'Type the message. Include important details like amounts, locations, or contact info.',
        targetSelector: 'textarea[data-slot="textarea"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'reminders-add-trigger',
        title: 'Trigger Date & Time',
        description: 'Set when the reminder should fire. Choose the date and time for the notification.',
        instruction: 'Pick the date and set the time. The reminder will trigger at the specified date and time.',
        targetSelector: 'input[data-slot="input"][type="date"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'reminders-add-submit',
        title: 'Creating the Reminder',
        description: 'Click "Create Reminder" to save. You\'ll be notified at the scheduled date and time.',
        instruction: 'Review all details. Click "Create Reminder" to schedule it.',
        targetSelector: 'button[type="submit"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'reminders-best-practices',
        title: 'Reminder Best Practices',
        description: 'Never miss important dates.',
        instruction: '• Check reminders at the start of each day\n• Act on reminders promptly\n• Use the notification settings to customize which reminders you receive\n• Review reminder settings periodically\n• Delete completed reminders to stay organized',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // USERS / EMPLOYEES — Employee, Account, Role forms (full version)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-users',
    screenPath: '/users',
    screenName: 'Users',
    title: 'User & Employee Management',
    description: 'Learn how to manage system users, employees, roles, permissions, and accounts.',
    estimatedDuration: 10,
    steps: [
      {
        id: 'users-welcome',
        title: 'Managing Users & Employees',
        description: 'This screen combines employee management with system accounts. Add employees, assign roles, and create login credentials.',
        instruction: 'The tabs switch between Employees, Accounts, and Roles. Only admins can access this screen.',
        targetSelector: 'div.flex.gap-1.p-1.rounded-xl.bg-muted\\/50.border',
        tooltipPosition: 'bottom',
      },
      // ── Full Employee Form ──
      {
        id: 'users-employee-open',
        title: 'Adding a New Employee',
        description: 'Click "Add Employee" on the Employees tab. Enter comprehensive employee information.',
        instruction: 'Click "Add Employee" to open the form with all fields.',
        targetSelector: 'button:has(svg.lucide-user-plus)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'users-employee-details',
        title: 'Employee Details',
        description: 'Fill in personal information: first name, last name, phone, email, role, and department.',
        instruction: 'Enter first name and last name (required). Add phone, email, select a role, and optional department.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'users-employee-employment',
        title: 'Employment & Location',
        description: 'Set employment status, gender, date of birth, hire date, and assign a warehouse.',
        instruction: 'Select employment status (Active/Inactive/Suspended). Optionally set gender, DOB, hire date, and warehouse assignment.',
        targetSelector: 'select',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'users-employee-emergency',
        title: 'Emergency Contact & Address',
        description: 'Record emergency contact info and residential address for HR purposes.',
        instruction: 'Enter emergency contact name/number. Add the employee\'s residential address and any HR notes.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'users-employee-submit',
        title: 'Creating the Employee',
        description: 'Click "Create Employee" to save the record. Then switch to the Accounts tab to create login credentials.',
        instruction: 'Review all details. Click "Create Employee" to save. The employee will appear in the list.',
        targetSelector: 'button[data-slot="button"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      // ── Account Form ──
      {
        id: 'users-account-open',
        title: 'Creating a Login Account',
        description: 'Switch to the Accounts tab. Click "Add Account" to create login credentials for an employee.',
        instruction: 'Click the "Accounts" tab, then "Add Account".',
        targetSelector: 'button:has(svg.lucide-user-cog)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'users-account-form',
        title: 'Account Credentials',
        description: 'Select the employee, set a unique username, and assign a PIN. Optionally force a password change on next login.',
        instruction: 'Select the employee from the dropdown. Enter a username and set a 4-digit PIN. Check "Force password change" for first-time users.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'users-account-submit',
        title: 'Creating the Account',
        description: 'Click "Create Account" to finalize. The employee can now log in.',
        instruction: 'Click "Create Account" to create the login credentials. Share credentials securely with the employee.',
        targetSelector: 'button[data-slot="button"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      // ── Role Form ──
      {
        id: 'users-role-open',
        title: 'Managing Roles',
        description: 'Switch to the Roles tab. Create roles with specific permission sets for different job functions.',
        instruction: 'Click the "Roles" tab, then "Add Role".',
        targetSelector: 'button:has(svg.lucide-shield)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'users-role-form',
        title: 'Role Name & Permissions',
        description: 'Name the role and select permissions from organized groups. Each permission controls access to a specific feature.',
        instruction: 'Enter a role name like "Cashier" or "Inventory Manager". Select permissions by clicking permission chips. Use "Select All" for full access.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'users-role-submit',
        title: 'Saving the Role',
        description: 'Click "Create Role" to save. Roles are available throughout the system for assignment.',
        instruction: 'Review selected permissions. Click "Create Role" to save.',
        targetSelector: 'button[data-slot="button"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'users-best-practices',
        title: 'User Management Best Practices',
        description: 'Keep your system secure.',
        instruction: '• Follow the principle of least privilege\n• Remove access immediately when employees leave\n• Use strong PINs for all users\n• Review user activity in audit logs\n• Review permissions quarterly\n• Keep employee information current',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // SUBSCRIPTION
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-subscription',
    screenPath: '/subscription',
    screenName: 'Subscription',
    title: 'Subscription Management',
    description: 'Learn how to view and manage your subscription plan, billing, and premium features.',
    estimatedDuration: 3,
    steps: [
      {
        id: 'subscription-welcome',
        title: 'Your Subscription',
        description: 'The Subscription Dashboard shows your current plan, billing details, and premium feature access.',
        instruction: 'Review your current plan, renewal date, and available premium features. Upgrade to unlock more capabilities.',
        targetSelector: 'div[data-slot="tabs-list"]',
        tooltipPosition: 'bottom',
      },
      {
        id: 'subscription-plans',
        title: 'Comparing Plans',
        description: 'Compare available plans and their features. Choose the plan that best matches your business needs.',
        instruction: 'Browse the available plans. Consider your current needs and future growth when choosing a plan.',
        targetSelector: 'button[data-slot="tabs-trigger"][value="plans"]',
        tooltipPosition: 'right',
      },
      {
        id: 'subscription-best-practices',
        title: 'Subscription Tips',
        description: 'Get the most from your subscription.',
        instruction: '• Evaluate your needs before upgrading\n• Take advantage of premium features you\'re paying for\n• Monitor your subscription renewal date\n• Contact support if you need a custom plan',
        tooltipPosition: 'center',
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // ADMIN MANAGEMENT — Admin form
  // ═══════════════════════════════════════════════════════════════
  {
    id: 'tutorial-admin-management',
    screenPath: '/admin-management',
    screenName: 'Admin Management',
    title: 'Admin Management',
    description: 'Learn how to manage system administrators, create admin accounts, and configure permissions.',
    estimatedDuration: 6,
    steps: [
      {
        id: 'admin-welcome',
        title: 'System Administration',
        description: 'The Admin Management screen is for super administrators only. It provides tools for managing admin accounts.',
        instruction: 'Review the admin list. Only super admins can access this screen.',
        targetSelector: 'div.overflow-auto.rounded-xl.border',
        tooltipPosition: 'bottom',
      },
      // ── Admin Form ──
      {
        id: 'admin-add-open',
        title: 'Creating an Admin',
        description: 'Click "Add Admin" to open the form. Enter their name, username, set a PIN, and assign permissions.',
        instruction: 'Click "Add Admin" to begin. Fields marked with * are required.',
        targetSelector: 'button:has(svg.lucide-plus)',
        tooltipPosition: 'left',
        waitForInteraction: true,
      },
      {
        id: 'admin-add-identity',
        title: 'Admin Identity',
        description: 'Enter the admin\'s display name and a unique username. The username is used for login.',
        instruction: 'Type the admin\'s full name (e.g. "Jane Smith"). Enter a username (e.g. "janesmith") — this must be unique in the system.',
        targetSelector: 'input[data-slot="input"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'admin-add-pin',
        title: 'Security PIN',
        description: 'Set a 4-digit PIN for the admin. The PIN is used for quick authentication. Confirm the PIN to avoid errors.',
        instruction: 'Enter a 4-digit PIN. Use the eye icon to toggle visibility. Confirm the PIN in the second field.',
        targetSelector: 'input[data-slot="input"][type="password"]',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'admin-add-permissions',
        title: 'Assigning Permissions',
        description: 'Select which modules and features this admin can access. Use "Select All" or choose individually.',
        instruction: 'Check permissions for the admin. Give only the access they need — you can always add more later. Use "Select All" for full access or toggle individual modules.',
        targetSelector: 'div.grid.grid-cols-2',
        tooltipPosition: 'bottom',
        waitForInteraction: true,
      },
      {
        id: 'admin-add-submit',
        title: 'Creating the Admin',
        description: 'Review the details and click "Create Admin" to save. The new admin can log in immediately.',
        instruction: 'Verify the name, username, and permissions. Click "Create Admin" to create the account. A recovery key will be generated.',
        targetSelector: 'button[type="submit"]',
        tooltipPosition: 'right',
        waitForInteraction: true,
      },
      {
        id: 'admin-best-practices',
        title: 'Super Admin Best Practices',
        description: 'Use admin powers responsibly.',
        instruction: '• Limit super admin access to essential personnel\n• Never share super admin credentials\n• Review all changes in audit logs\n• Have a recovery plan for admin access\n• Change default PINs on first login',
        tooltipPosition: 'center',
      },
    ],
  },
];

const fallbackTutorial: ScreenTutorial = {
  id: 'tutorial-generic',
  screenPath: '*',
  screenName: 'General',
  title: 'Screen Overview',
  description: 'Learn about the key features available on this screen.',
  estimatedDuration: 2,
  steps: [
    {
      id: 'generic-welcome',
      title: 'Getting Started',
      description: 'This screen provides tools and information to help you manage your business. Each section is designed for specific tasks.',
      instruction: 'Explore the interface. Look for buttons, tabs, and data tables that help you accomplish your tasks.',
      tooltipPosition: 'center',
    },
    {
      id: 'generic-actions',
      title: 'Available Actions',
      description: 'Look for action buttons like Add, Edit, Delete, and Export. These let you manage data on this screen.',
      instruction: 'Buttons are typically at the top of the screen. Look for the Plus icon to add new items.',
      tooltipPosition: 'center',
    },
    {
      id: 'generic-best-practices',
      title: 'Need More Help?',
      description: 'For detailed guidance, check the documentation or contact support. Every screen is designed to be intuitive.',
      instruction: 'If you\'re unsure about a feature, try it with sample data. You can always cancel or undo most actions.',
      tooltipPosition: 'center',
    },
  ],
};

export function getTutorialForPath(path: string): ScreenTutorial | undefined {
  const normalizedPath = path.split('?')[0].split('#')[0];
  const tutorial = tutorials.find((t) => {
    if (t.screenPath === normalizedPath) return true;
    if (t.screenPath.endsWith('*')) {
      const base = t.screenPath.slice(0, -1);
      return normalizedPath.startsWith(base);
    }
    return false;
  });
  return tutorial;
}

export function getTutorialById(id: string): ScreenTutorial | undefined {
  return tutorials.find((t) => t.id === id);
}

export function getAllTutorials(): ScreenTutorial[] {
  return tutorials;
}

export { fallbackTutorial, tutorials };
